import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { MdCheckCircle, MdLock } from 'react-icons/md';
import { api } from '../lib/api';
import '../styles/auth.css';

function ResetPassword() {
  const [params] = useSearchParams(); const token = params.get('token'); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [error, setError] = useState(''); const [complete, setComplete] = useState(false); const [saving, setSaving] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (!token) { setError('This reset link is invalid. Request a new one.'); return; } if (password.length < 8) { setError('Password must be at least 8 characters.'); return; } if (password !== confirmPassword) { setError('Passwords do not match.'); return; } try { setSaving(true); setError(''); await api.resetPassword(token, password); setComplete(true); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  return <div className="auth-container"><div className="auth-card recovery-card">{complete ? <div className="recovery-message"><span><MdCheckCircle /></span><h1>Password updated</h1><p>Your existing sessions have been signed out. Log in with your new password.</p><Link className="auth-btn recovery-link" to="/login">Continue to login</Link></div> : <><div className="auth-header"><p className="auth-brand">Deplug Social</p><h1>Create a new password</h1><p>Choose a strong password of at least 8 characters.</p></div>{error && <div className="auth-error">{error}</div>}<form className="auth-form" onSubmit={submit}><div className="form-group"><label>New password</label><div className="input-wrapper"><span className="input-icon"><MdLock /></span><input required minLength="8" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Create a password" /></div></div><div className="form-group"><label>Confirm new password</label><div className="input-wrapper"><span className="input-icon"><MdLock /></span><input required type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} placeholder="Confirm your password" /></div></div><button className="auth-btn" disabled={saving} type="submit">{saving ? 'Updating password…' : 'Update password'}</button></form></>}</div></div>;
}
export default ResetPassword;
